   route:
     group_by: ['alertname']
     group_wait: 30s
     group_interval: 5m
     repeat_interval: 3h
     receiver: 'default'

     routes:
       - matchers:
           - severity = "critical"
         receiver: 'critical-email'

       - matchers:
           - severity = "warning"
         receiver: 'warning-email'

   receivers:
     - name: 'critical-email'
       email_configs:
         - to: 'critical@mail'
           from: 'alertmanager@example.com'
           smarthost: 'smtp.example.com:587'
           auth_username: 'smtp_user'
           auth_identity: 'smtp_user'
           auth_password: 'smtp_password'

     - name: 'warning-email'
       email_configs:
         - to: 'warning@mail'
           from: 'alertmanager@example.com'
           smarthost: 'smtp.example.com:587'
           auth_username: 'smtp_user'
           auth_identity: 'smtp_user'
           auth_password: 'smtp_password'

     - name: 'default'
       email_configs:
         - to: 'default@mail'
           from: 'alertmanager@example.com'
           smarthost: 'smtp.example.com:587'
           auth_username: 'smtp_user'
           auth_identity: 'smtp_user'
           auth_password: 'smtp_password'

